# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenML Server
site_url: https://openml.github.io/server-api

repo_name: openml/server-api
repo_url: https://github.com/openml/server-api

theme:
  name: material

  features:
    - content.code.copy

nav:
  - Getting Started: installation.md
  - Contributing:
      - contributing/index.md
      - Development: contributing/contributing.md
      - Tests: contributing/tests.md
      - Documentation: contributing/documentation.md
      - Project Overview: contributing/project_overview.md
  - Changes: migration.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - tables

plugins:
  - section-index
