# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenML Server
site_url: https://openml.github.io/server-api

repo_name: openml/server-api
repo_url: https://github.com/openml/server-api

theme:
  name: material
  features:
    - content.code.copy
    - navigation.indexes
    - navigation.sections
    - navigation.tabs

nav:
  - OpenML Server:
      - index.md
      - Migration Guide: migration.md
      - Roadmap: roadmap.md
  - Deployment:
      - installation.md
  - Development:
      - Project Overview: development/project_overview.md
      - Development:
        - "Development Environment": development/setup.md
        - "Writing Code": development/code.md
        - "Writing Tests": development/tests.md
        - "CI/CD": development/CI_CD.md
        - Documentation: development/documentation.md
      - Database:
        - development/database/index.md
        - openml: development/database/openml.md
        - openml_expdb: development/database/openml_expdb.md
  - Contributing:
      - contributing/index.md
      - Code of Conduct: contributing/code_of_conduct.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - tables

plugins:
  - search
  - section-index
