PRIVATE_DATASET_ID = {130}
IN_PREPARATION_ID = {1, 33}
DEACTIVATED_DATASETS = {2, 131}
DATASETS = set(range(1, 132))

NUMBER_OF_DATASETS = len(DATASETS)
NUMBER_OF_DEACTIVATED_DATASETS = len(DEACTIVATED_DATASETS)
NUMBER_OF_DATASETS_IN_PREPARATION = len(IN_PREPARATION_ID)
NUMBER_OF_PRIVATE_DATASETS = len(PRIVATE_DATASET_ID)
NUMBER_OF_ACTIVE_DATASETS = (
    NUMBER_OF_DATASETS - NUMBER_OF_DEACTIVATED_DATASETS - NUMBER_OF_DATASETS_IN_PREPARATION
)
NUMBER_OF_PUBLIC_ACTIVE_DATASETS = NUMBER_OF_ACTIVE_DATASETS - NUMBER_OF_PRIVATE_DATASETS
