PRIVATE_DATASET_ID = {130}
IN_PREPARATION_ID = {33, 161, 162, 163}
DEACTIVATED_DATASETS = {131}
DATASETS = set(range(1, 132)) | {161, 162, 163}

NUMBER_OF_DATASETS = len(DATASETS)
NUMBER_OF_DEACTIVATED_DATASETS = len(DEACTIVATED_DATASETS)
NUMBER_OF_DATASETS_IN_PREPARATION = len(IN_PREPARATION_ID)
NUMBER_OF_PRIVATE_DATASETS = len(PRIVATE_DATASET_ID)
NUMBER_OF_ACTIVE_DATASETS = (
    NUMBER_OF_DATASETS - NUMBER_OF_DEACTIVATED_DATASETS - NUMBER_OF_DATASETS_IN_PREPARATION
)
NUMBER_OF_PUBLIC_ACTIVE_DATASETS = NUMBER_OF_ACTIVE_DATASETS - NUMBER_OF_PRIVATE_DATASETS
