blank_issues_enabled: true
contact_links:
  - name: 📖 Documentation
    url: https://openml.github.io/server-api
    about: Read our documentation -- it answers many questions!
  - name: 💬 Ask on Github
    url: https://github.com/openml/server-api/discussions/new?category=q-a
    about: For all questions on the OpenML REST API.
  - name: 💬 Ask on Slack
    url: https://join.slack.com/t/openml/shared_invite/enQtODg4NjgzNTE4NjU3LTYwZDFhNzQ5NmE0NjIyNmM3NDMyMjFkZDQ0YWZkYWYxMTIxODFmMDhhMTUzMGYzMmM4NjIzYTZlYjBkOGE5MTQ
    about: Get in touch with the whole OpenML community.
