arff_base_url="https://test.openml.org"
minio_base_url="https://openml1.win.tue.nl"

[development]
allow_test_api_keys=true

# Any number of logging.NAME configurations can be added.
# NAME is for reference only, it has no meaning otherwise.
# You can add any arguments to `loguru.logger.add`,
# the `sink` variable will be used as first positional argument.
# https://loguru.readthedocs.io/en/stable/api/logger.html
[logging.develop]
sink="develop.log"
# One of loguru levels: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR
level="DEBUG"
# Automatically create a new file by date or file size
rotation="50 MB"
# Retention specifies the timespan after which automatic cleanup occurs.
retention="1 day"
compression="gz"

[fastapi]
root_path=""

[databases.defaults]
host="database"
port="3306"
# SQLAlchemy `dialect` and `driver`: https://docs.sqlalchemy.org/en/20/dialects/index.html
drivername="mysql+aiomysql"

[databases.expdb]
database="openml_expdb"

[databases.openml]
database="openml"

[routing]
minio_url="http://minio:9000/"
server_url="http://php-api:80/"

[run]
evaluation_engine_ids = [1]
