[development]
allow_test_api_keys=true

# Any number of logging.NAME configurations can be added.
# NAME is for reference only, it has no meaning otherwise.
# You can add any arguments to `loguru.logger.add`,
# the `sink` variable will be used as first positional argument.
# https://loguru.readthedocs.io/en/stable/api/logger.html

# Any number of logging.NAME configurations can be added.
# NAME is for reference only, it has no meaning otherwise.
[logging.develop]
sink="develop.log"
# One of loguru levels: TRACE, DEBUG, INFO, SUCCESS, WARNING, ERROR
level="DEBUG"
rotation="50 MB"
# Retention specifies the timespan after which automatic cleanup occurs.
retention="1 day"
compression="gz"

[databases.expdb]
database="openml_expdb"

[databases.openml]
database="openml"

[routing]
root_path=""
minio_url="http://minio:9000/"
server_url="http://php-api:80/"
