name: Tests
on:
  push:
    branches:
      - main
      - test/ci

permissions:
  contents: write

jobs:
  compare-php:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: docker compose --parallel 8 up -d --wait php-api python-api
      - run: docker container ls
      - run: docker exec python-api python -m pytest -xv -m "php"
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: docker compose up -d --wait database python-api
      - run: docker container ls
      - run: docker exec python-api python -m pytest -xv -m "not php"
