# https://squidfunk.github.io/mkdocs-material/publishing-your-site/?h=#with-github-actions
name: Deploy Docs
on:
  push:
    branches:
      - main
      - test/ci

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: docker compose up -d --wait
      - run: docker container ls
      - run: docker exec python-api python -m pytest -xv -m "php"
